from fastapi import APIRouter, HTTPException, Query
from services.supabase_service import get_latest_cloud_reading, get_cloud_history

router = APIRouter(prefix="/api/aqi", tags=["AQI Telemetry"])

@router.get("/current")
async def current_aqi():
    try:
        data = await get_latest_cloud_reading()
        if not data:
            raise HTTPException(status_code=404, detail="No AQI sensor data available from cloud.")
        return {"status": "success", "data": data}
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Cloud telemetry connection error: {str(e)}")

@router.get("/forecast")
async def aqi_forecast():
    """
    24-hour predictive air quality forecast strictly generated by the
    trained Bidirectional Seq2Seq LSTM model in aqi_model_and_calibrators.
    """
    try:
        from services.lstm_forecast_service import generate_24h_lstm_forecast
        data = await generate_24h_lstm_forecast()
        return data
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"LSTM Forecast Engine error: {str(e)}")

@router.get("/predict-24h")
async def aqi_predict_24h():
    """Dedicated alias for 24-hour LSTM forecast"""
    try:
        from services.lstm_forecast_service import generate_24h_lstm_forecast
        data = await generate_24h_lstm_forecast()
        return data
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"LSTM Forecast Engine error: {str(e)}")

@router.get("/historical")
async def aqi_historical(limit: int = Query(default=50, ge=1, le=500)):
    try:
        history = await get_cloud_history(limit=limit)
        return {"status": "success", "count": len(history), "history": history}
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Cloud telemetry connection error: {str(e)}")

@router.get("/comparison")
async def aqi_comparison(history_limit: int = Query(default=48, ge=12, le=96)):
    """
    Returns comparative analytics between LSTM forecast and AQI Historical Telemetry
    matched on identical time points. Future hours have blank/null actual values,
    which are dynamically populated when data arrives.
    """
    try:
        from services.lstm_forecast_service import get_aligned_comparison_data
        data = await get_aligned_comparison_data(history_limit=history_limit)
        return data
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Comparison Engine error: {str(e)}")


